### PR TITLE
SUPPORT FOR JUNIT 5

### PR DESCRIPTION
**Pull request by rses**
I'VE DONE LITTLE WORK TO GET JFIXTURE WORKING WITH JUNIT5, BUT IT COMES TWO-FOLDS:

1. CLEANED UP DEPENDENCIES SO THAT I CAN USE JUPITER AS A MODULE
2. ADDED `FixtureExtension` THAT JUPITER :heart: 

I'VE NOT ADDED SUPPORT FOR CUSTOMISATIONS AS YET AS I DON'T NEED THEM FOR MY USE CASE AT THE MOMENT. ADDING CUSTOMISATIONS WILL BE EASY AS JUPITER HAS `RegisterExtension` WHICH CAN BE USED TO MODIFY JFIXTURE

### CODE REVIEW

**Comment by rses** [comment]
HANG ON, MY TESTS ARE NOT RUNNING

**Comment by rses** [comment]
IT'S RUNNING NOW :smile:

**Comment by rses** [comment]
Does anyone want to do this? :pray:

**Comment by philipwhiuk** [comment]
LGTM

**Comment by rses** [comment]
Cheers Phil :smile:

Is it right that I'm seeing the last release done was September 2017? Can we get a release with the Jupiter stuff please?

Also, I was going to update the documentation, however, that's on the wiki, which I don't have permission on - how would I go about doing this?

**Comment by philipwhiuk** [comment]
Regarding the release I shall investigate how to go about doing that.

In terms of the documentation I think you have to be on the team... (PRs for Wiki pages plz GitHub). I've invited you.

**Pull request merged**
